language: java

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

jdk:
  - oraclejdk11

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C $HOME/bin

script:
  - mvn clean test
